CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    dish_name VARCHAR(255) NOT NULL,
    times_ordered INTEGER DEFAULT 0,
    revenue DECIMAL(10, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_balance (
    id SERIAL PRIMARY KEY,
    balance DECIMAL(10, 2) DEFAULT 0.00,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO user_balance (balance) VALUES (1000.00);